package emoji

import (
	"embed"
	"encoding/csv"
	"fmt"
	"io/fs"
	"slices"
	"strconv"
	"strings"
)

//go:embed data/catalog.txt data/types.txt data/themes.txt
var dataFS embed.FS

// suggestionGroups are the Unicode groups the reference repository actually
// draws commit emoji from, measured by usage: Objects, Travel & Places,
// Animals & Nature, Food & Drink and Activities account for nearly every
// commit, while People & Body accounts for eight in total. Membership decides
// what may be SUGGESTED, never what is allowed.
var suggestionGroups = []string{
	"Objects",
	"Travel & Places",
	"Animals & Nature",
	"Food & Drink",
	"Activities",
}

// suggestionSubgroups admits the meaningful corners of groups that are
// otherwise too noisy to recommend from: Symbols without its arrows, zodiac
// signs and keycaps, Flags without countries, and the monkey faces, which read
// as "hide this" and "quiet this down" far better than anything in Objects.
var suggestionSubgroups = []string{
	"other-symbol",
	"warning",
	"punctuation",
	"av-symbol",
	"flag",
	"monkey-face",
}

// Catalog is the set of commit emoji this project accepts, plus the narrower
// pool it is willing to recommend. Build it with NewCatalog.
type Catalog struct {
	allowed map[string]entry
	pool    []string
	inPool  map[string]bool
	byType  map[string][]string
}

type entry struct {
	group     string
	subgroup  string
	janeCount int
}

// NewCatalog builds the catalog from the embedded data files. The data is
// generated by tools/emojigen and validated by this package's tests, which
// assert the entry counts; a malformed record is a build-time defect in that
// generator's output, so NewCatalog reports it as an error rather than
// silently returning a narrower - or, on a parse failure, entirely empty -
// catalog.
func NewCatalog() (*Catalog, error) {
	catalog := &Catalog{
		allowed: make(map[string]entry, 1100),
		byType:  make(map[string][]string, 16),
	}
	if err := catalog.readCatalog(); err != nil {
		return nil, err
	}
	if err := catalog.readTypes(); err != nil {
		return nil, err
	}
	catalog.buildPool()
	return catalog, nil
}

func (c *Catalog) readCatalog() error {
	records, err := readRecords(dataFS, "data/catalog.txt", 4)
	if err != nil {
		return err
	}
	for _, fields := range records {
		count, countErr := strconv.Atoi(fields[3])
		if countErr != nil {
			continue
		}
		c.allowed[fields[0]] = entry{group: fields[1], subgroup: fields[2], janeCount: count}
	}
	return nil
}

func (c *Catalog) readTypes() error {
	records, err := readRecords(dataFS, "data/types.txt", 3)
	if err != nil {
		return err
	}
	for _, fields := range records {
		commitType, shortcode := fields[0], fields[1]
		if _, ok := c.allowed[shortcode]; !ok {
			continue
		}
		c.byType[commitType] = append(c.byType[commitType], shortcode)
	}
	return nil
}

// buildPool ranks the recommendable shortcodes by measured usage so the head of
// the list carries the strongest signal and the tail stays available for
// variety.
func (c *Catalog) buildPool() {
	c.pool = make([]string, 0, len(c.allowed))
	for shortcode, info := range c.allowed {
		// Measured usage outranks the group lists: an emoji real commits
		// already reached for is proven to read as an engineering area, wherever
		// Unicode happens to file it.
		if info.janeCount > 0 ||
			slices.Contains(suggestionGroups, info.group) ||
			slices.Contains(suggestionSubgroups, info.subgroup) {
			c.pool = append(c.pool, shortcode)
		}
	}
	slices.SortFunc(c.pool, func(a, b string) int {
		if diff := c.allowed[b].janeCount - c.allowed[a].janeCount; diff != 0 {
			return diff
		}
		return strings.Compare(a, b)
	})

	c.inPool = make(map[string]bool, len(c.pool))
	for _, shortcode := range c.pool {
		c.inPool[shortcode] = true
	}
}

// Allows reports whether a shortcode may lead a commit subject.
func (c *Catalog) Allows(shortcode string) bool {
	_, found := c.allowed[shortcode]
	return found
}

// Size returns the number of allowed shortcodes.
func (c *Catalog) Size() int { return len(c.allowed) }

// PoolSize returns the number of shortcodes eligible to be suggested.
func (c *Catalog) PoolSize() int { return len(c.pool) }

// readRecords takes fsys rather than always reading the package-level dataFS
// so tests can point it at a fabricated fs.FS instead of corrupting the real
// embedded data.
func readRecords(fsys fs.FS, name string, fieldCount int) ([][]string, error) {
	file, err := fsys.Open(name)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", name, err)
	}
	defer func() { _ = file.Close() }()

	reader := csv.NewReader(file)
	reader.Comma = '\t'
	reader.Comment = '#'
	reader.FieldsPerRecord = fieldCount

	records, err := reader.ReadAll()
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", name, err)
	}
	return records, nil
}
