package main

import (
	"fmt"
	"maps"
	"os"
	"slices"
	"strings"

	"github.com/0b1-PulsarTech/pulsarules_codex/internal/emoji"
	"github.com/0b1-PulsarTech/pulsarules_codex/internal/fsperm"
)

const catalogHeader = "# name\tgroup\tsubgroup\tjane_count\n" +
	"# Generated by tools/emojigen. Do not edit by hand.\n"

const typesHeader = "# type\tname\tcount\n" +
	"# Generated by tools/emojigen. Do not edit by hand.\n"

// maxEmojiVersion is the rendering cutoff. The owner's GitKraken shows newer
// emoji as raw text, and E1.0 is the boundary that reproduces the measured
// evidence exactly: every shortcode confirmed broken by hand sits above it,
// and 286 of the reference repository's 295 sit at or below it.
const maxEmojiVersion = 1.0

// janeExceptions are shortcodes above the version cutoff that the reference
// repository uses anyway, kept by explicit decision. They are the candidates to
// re-check first if raw text shows up in a commit list again.
var janeExceptions = []string{"beetle", "egg", "safety_vest", "shopping_cart", "pirate_flag"}

// excludedSubgroups drops country flags, which carry no engineering meaning and
// would crowd the catalog. Non-country flags (checkered_flag, crossed_flags)
// stay.
var excludedSubgroups = []string{"country-flag", "subdivision-flag"}

type catalogEntry struct {
	Name      string
	Version   float64
	Group     string
	Subgroup  string
	JaneCount int
}

func buildCatalog(
	shortcodes map[string]string,
	meta map[string]unicodeMeta,
	janeCounts map[string]int,
) []catalogEntry {
	entries := make([]catalogEntry, 0, len(shortcodes))
	for name, codepoints := range shortcodes {
		sequenceMeta, ok := lookupMeta(meta, codepoints)
		if !ok {
			continue
		}
		if !admits(name, sequenceMeta) {
			continue
		}
		entries = append(entries, catalogEntry{
			Name:      name,
			Version:   sequenceMeta.Version,
			Group:     sequenceMeta.Group,
			Subgroup:  sequenceMeta.Subgroup,
			JaneCount: janeCounts[name],
		})
	}
	slices.SortFunc(entries, func(a, b catalogEntry) int { return strings.Compare(a.Name, b.Name) })
	return entries
}

func admits(name string, sequenceMeta unicodeMeta) bool {
	if emoji.IsProhibited(name) || emoji.IsNonRendering(name) {
		return false
	}
	if slices.Contains(excludedSubgroups, sequenceMeta.Subgroup) {
		return false
	}
	return sequenceMeta.Version <= maxEmojiVersion || slices.Contains(janeExceptions, name)
}

// lookupMeta tolerates the spelling differences between GitHub's codepoint
// URLs and the Unicode data file: a missing variation selector, and joined
// sequences written without their zero-width joiners.
func lookupMeta(meta map[string]unicodeMeta, codepoints string) (unicodeMeta, bool) {
	for _, candidate := range []string{
		codepoints,
		stripJoiners(codepoints),
		codepoints + "-fe0f",
	} {
		if sequenceMeta, ok := meta[candidate]; ok {
			return sequenceMeta, true
		}
	}
	return unicodeMeta{}, false
}

func writeCatalog(path string, entries []catalogEntry) error {
	var buf strings.Builder
	buf.WriteString(catalogHeader)
	for _, entry := range entries {
		_, _ = fmt.Fprintf(&buf, "%s\t%s\t%s\t%d\n",
			entry.Name,
			entry.Group,
			entry.Subgroup,
			entry.JaneCount,
		)
	}
	if err := os.WriteFile(path, []byte(buf.String()), fsperm.FilePrivate); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func writeTypes(path string, byType map[string]map[string]int, allowed map[string]bool) error {
	var buf strings.Builder
	buf.WriteString(typesHeader)
	for _, commitType := range slices.Sorted(maps.Keys(byType)) {
		for _, entry := range rankedCounts(byType[commitType], allowed) {
			_, _ = fmt.Fprintf(&buf, "%s\t%s\t%d\n", commitType, entry.name, entry.count)
		}
	}
	if err := os.WriteFile(path, []byte(buf.String()), fsperm.FilePrivate); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

type rankedEntry struct {
	name  string
	count int
}

// rankedCounts orders by descending usage, then by name so the generated file
// is stable across runs.
func rankedCounts(counts map[string]int, allowed map[string]bool) []rankedEntry {
	ranked := make([]rankedEntry, 0, len(counts))
	for name, count := range counts {
		if allowed[name] {
			ranked = append(ranked, rankedEntry{name: name, count: count})
		}
	}
	slices.SortFunc(ranked, func(a, b rankedEntry) int {
		if a.count != b.count {
			return b.count - a.count
		}
		return strings.Compare(a.name, b.name)
	})
	return ranked
}
