package hook

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/0b1-PulsarTech/pulsarules_codex/internal/analysis"
	"github.com/0b1-PulsarTech/pulsarules_codex/internal/fsperm"
	"github.com/0b1-PulsarTech/pulsarules_codex/internal/vcs"
)

func TestRunGovernanceCheck_EmptyRepo(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	if out, err := exec.CommandContext(t.Context(), "git", "-C", dir, "init").
		CombinedOutput(); err != nil {
		t.Fatalf("git init: %v\n%s", err, out)
	}
	repo, err := vcs.Open(dir)
	if err != nil {
		t.Fatalf("vcs.Open: %v", err)
	}
	status, err := repo.WorktreeStatus()
	if err != nil {
		t.Fatalf("WorktreeStatus: %v", err)
	}

	// A repository with no commits and no changes has no findings, so the
	// pipeline must stay quiet rather than fail: an empty block and a zero
	// count, exactly.
	got, count := RunGovernanceCheck(repo, status, nil, analysis.ScopeChanged)
	if got != "" {
		t.Errorf("block = %q, want empty for an empty repo", got)
	}
	if count != 0 {
		t.Errorf("count = %d, want 0 for an empty repo", count)
	}
}

// TestRunGovernanceCheck_SuppressionIsStated pins the hook half of the rule
// the CLI footer carries: the block has no footer of its own, so it has to say
// how many findings the generated-file filter removed, or a filtered report
// reads as a clean one.
func TestRunGovernanceCheck_SuppressionIsStated(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	gitInit(t, dir)
	// Two files with the same defect: one generated, one hand-written. The
	// hand-written one keeps the block non-empty so the suppression line has
	// somewhere to appear.
	emDash := "\u2014"
	writeFile(
		t, dir, "gen.go",
		"// Code generated by sqlc. DO NOT EDIT.\n\npackage x\n\n// a "+emDash+" b\n",
	)
	writeFile(t, dir, "hand.go", "package x\n\n// c "+emDash+" d\n")

	repo, err := vcs.Open(dir)
	if err != nil {
		t.Fatalf("vcs.Open: %v", err)
	}
	status, err := repo.WorktreeStatus()
	if err != nil {
		t.Fatalf("WorktreeStatus: %v", err)
	}

	block, count := RunGovernanceCheck(repo, status, nil, analysis.ScopeChanged)
	if count != 1 {
		t.Fatalf("count = %d, want 1 (the generated file's finding is suppressed)", count)
	}
	if !strings.Contains(block, "1 finding(s) suppressed in generated files") {
		t.Fatalf("block does not state the suppression:\n%s", block)
	}
}

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()

	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), fsperm.File); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
}
