package core

import "testing"

type generatedTestCase struct {
	name string
	src  string
	want bool
}

func TestIsGeneratedSource(t *testing.T) {
	t.Parallel()

	testCases := append(generatedMarkerCases(), generatedNonMarkerCases()...)
	for _, testCase := range testCases {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()
			if got := IsGeneratedSource([]byte(testCase.src)); got != testCase.want {
				t.Fatalf("IsGeneratedSource(%q) = %v, want %v", testCase.src, got, testCase.want)
			}
		})
	}
}

func generatedMarkerCases() []generatedTestCase {
	return []generatedTestCase{
		{
			name: "marker on the first line",
			src:  "// Code generated by sqlc. DO NOT EDIT.\n\npackage dbgen\n",
			want: true,
		},
		{
			name: "marker after a build tag and a blank line",
			src: "//go:build !windows\n\n" +
				"// Code generated by mockgen. DO NOT EDIT.\n\npackage notifier\n",
			want: true,
		},
		{
			name: "mockgen header naming source and destination",
			src: "// Code generated by MockGen. DO NOT EDIT.\n" +
				"// Source: dispatcher.go\n\npackage notifier\n",
			want: true,
		},
		{
			name: "crlf line endings",
			src:  "// Code generated by sqlc. DO NOT EDIT.\r\n\r\npackage dbgen\r\n",
			want: true,
		},
		{
			name: "final line carries the marker without a newline",
			src:  "// Code generated by sqlc. DO NOT EDIT.",
			want: true,
		},
		{
			name: "license block comment before the marker",
			src: "/*\nCopyright 2024.\n*/\n\n" +
				"// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage x\n",
			want: true,
		},
		{
			name: "block comment on one line before the marker",
			src: "/* Copyright 2024 */\n\n" +
				"// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage x\n",
			want: true,
		},
	}
}

func TestIsExemptHeaderLine(t *testing.T) {
	t.Parallel()

	testCases := []struct {
		name string
		line string
		want bool
	}{
		{
			name: "generated marker",
			line: "// Code generated by sqlc. DO NOT EDIT.",
			want: true,
		},
		{name: "go build tag", line: "//go:build linux", want: true},
		{name: "legacy build tag", line: "// +build linux", want: true},
		{name: "leading whitespace before the tag", line: "  //go:build linux", want: true},
		{name: "package clause", line: "package foo", want: false},
		{name: "ordinary comment", line: "// a helper", want: false},
		{
			name: "marker without the trailing period is not exempt",
			line: "// Code generated by sqlc. DO NOT EDIT",
			want: false,
		},
	}
	for _, testCase := range testCases {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()
			if got := IsExemptHeaderLine(testCase.line); got != testCase.want {
				t.Fatalf("IsExemptHeaderLine(%q) = %v, want %v", testCase.line, got, testCase.want)
			}
		})
	}
}

func generatedNonMarkerCases() []generatedTestCase {
	return []generatedTestCase{
		{
			name: "marker below the package clause is not honoured",
			src:  "package dbgen\n\n// Code generated by sqlc. DO NOT EDIT.\n",
			want: false,
		},
		{
			name: "marker without the trailing period",
			src:  "// Code generated by sqlc. DO NOT EDIT\n\npackage dbgen\n",
			want: false,
		},
		{
			name: "sql-style marker is not the Go convention",
			src:  "-- Code generated by sqlc. DO NOT EDIT.\n\nSELECT 1;\n",
			want: false,
		},
		{
			name: "prose mentioning generation is not a marker",
			src:  "// This file was generated once. Do not edit.\n\npackage x\n",
			want: false,
		},
		{
			name: "prefix and suffix must not overlap on a short line",
			src:  "// Code generated DO NOT EDIT.\n\npackage x\n",
			want: false,
		},
		{
			name: "hand-written file",
			src:  "// Package doc.\npackage x\n\nfunc F() {}\n",
			want: false,
		},
		{
			name: "empty file",
			src:  "",
			want: false,
		},
		{
			name: "comments only, no marker",
			src:  "// a\n// b\n",
			want: false,
		},
		{
			name: "marker written inside a block comment",
			src:  "/* Code generated by x. DO NOT EDIT. */\n\npackage x\n",
			want: false,
		},
		{
			name: "block comment that never closes",
			src:  "/*\nnever closes\n",
			want: false,
		},
		{
			name: "block comment closes then the package clause is reached",
			src: "/* c */ package x\n\n" +
				"// Code generated by sqlc. DO NOT EDIT.\n",
			want: false,
		},
	}
}
