package analysis

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/0b1-PulsarTech/pulsarules_codex/internal/analyzer/core"
	"github.com/0b1-PulsarTech/pulsarules_codex/internal/fsperm"
)

const (
	markGeneratedContent = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage x\n"
	markPlainContent     = "package x\n\nfunc F() {}\n"
)

type markGeneratedTestCase struct {
	name     string
	setup    func(t *testing.T, dir string) []core.FileChange
	sources  func(dir string) core.SourceProvider
	wantFlag []bool
}

func TestMarkGenerated(t *testing.T) {
	t.Parallel()

	testCases := markGeneratedTestCases()
	for _, testCase := range testCases {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()
			dir := t.TempDir()
			files := testCase.setup(t, dir)
			markGenerated(files, testCase.sources(dir))
			if len(files) != len(testCase.wantFlag) {
				t.Fatalf("got %d files, want %d", len(files), len(testCase.wantFlag))
			}
			for i, want := range testCase.wantFlag {
				if files[i].Generated != want {
					t.Errorf("files[%d].Generated = %v, want %v", i, files[i].Generated, want)
				}
			}
		})
	}
}

func markGeneratedTestCases() []markGeneratedTestCase {
	return []markGeneratedTestCase{
		{
			name: "mixed generated and non-generated files",
			setup: func(t *testing.T, dir string) []core.FileChange {
				t.Helper()
				writeMarkGeneratedFile(t, dir, "generated.go", markGeneratedContent)
				writeMarkGeneratedFile(t, dir, "plain.go", markPlainContent)
				return []core.FileChange{
					{Path: "generated.go", Extension: ".go"},
					{Path: "plain.go", Extension: ".go"},
				}
			},
			sources:  core.NewSourceProvider,
			wantFlag: []bool{true, false},
		},
		{
			name: "nil sources leaves flags false",
			setup: func(t *testing.T, dir string) []core.FileChange {
				t.Helper()
				writeMarkGeneratedFile(t, dir, "generated.go", markGeneratedContent)
				return []core.FileChange{{Path: "generated.go", Extension: ".go"}}
			},
			sources:  func(string) core.SourceProvider { return nil },
			wantFlag: []bool{false},
		},
		{
			name: "path that does not exist leaves flag false",
			setup: func(t *testing.T, dir string) []core.FileChange {
				t.Helper()
				return []core.FileChange{{Path: "missing.go", Extension: ".go"}}
			},
			sources:  core.NewSourceProvider,
			wantFlag: []bool{false},
		},
	}
}

func writeMarkGeneratedFile(t *testing.T, dir, relPath, content string) {
	t.Helper()
	full := filepath.Join(dir, relPath)
	if err := os.WriteFile(full, []byte(content), fsperm.File); err != nil {
		t.Fatalf("write %q: %v", full, err)
	}
}
