package analysis

import (
	"testing"

	"github.com/0b1-PulsarTech/pulsarules_codex/internal/analyzer/core"
	"github.com/0b1-PulsarTech/pulsarules_codex/internal/config"
	"github.com/0b1-PulsarTech/pulsarules_codex/internal/vcs"
)

type splitTestCase struct {
	name           string
	files          []core.FileChange
	findings       []core.Finding
	wantKept       []string
	wantSuppressed int
}

// generatedFiles is the file set every split case is judged against: two
// generated files and one hand-written.
func generatedFiles() []core.FileChange {
	return []core.FileChange{
		{Path: "internal/dbgen/lead.sql.go", Extension: ".go", Generated: true},
		{Path: "internal/dbgen/task.sql.go", Extension: ".go", Generated: true},
		{Path: "internal/repo/lead.go", Extension: ".go"},
	}
}

func TestSplitGenerated(t *testing.T) {
	t.Parallel()

	for _, testCase := range splitTestCases() {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()

			ctx := &core.AnalysisContext{ChangedFiles: testCase.files}
			got := splitGenerated(ctx, testCase.findings)
			if got.SuppressedGenerated != testCase.wantSuppressed {
				t.Fatalf(
					"SuppressedGenerated = %d, want %d",
					got.SuppressedGenerated,
					testCase.wantSuppressed,
				)
			}
			if len(got.Findings) != len(testCase.wantKept) {
				t.Fatalf(
					"kept %d findings, want %d: %+v",
					len(got.Findings),
					len(testCase.wantKept),
					got.Findings,
				)
			}
			for i, want := range testCase.wantKept {
				if got.Findings[i].File != want {
					t.Errorf("kept[%d].File = %q, want %q", i, got.Findings[i].File, want)
				}
			}
		})
	}
}

func splitTestCases() []splitTestCase {
	files := generatedFiles()
	return []splitTestCase{
		{
			name:  "findings in generated files are suppressed and counted",
			files: files,
			findings: []core.Finding{
				{AnalyzerID: "shadowing", File: "internal/dbgen/lead.sql.go", Line: 12},
				{AnalyzerID: "shadowing", File: "internal/dbgen/task.sql.go", Line: 8},
				{AnalyzerID: "naming", File: "internal/repo/lead.go", Line: 4},
			},
			wantKept:       []string{"internal/repo/lead.go"},
			wantSuppressed: 2,
		},
		{
			name:  "a finding with no file is never suppressed",
			files: files,
			findings: []core.Finding{
				{AnalyzerID: "commit-lint", File: ""},
				{AnalyzerID: "file-size", File: "internal/dbgen/lead.sql.go"},
			},
			wantKept:       []string{""},
			wantSuppressed: 1,
		},
		{
			name:  "no generated file means nothing is filtered",
			files: []core.FileChange{{Path: "internal/repo/lead.go", Extension: ".go"}},
			findings: []core.Finding{
				{AnalyzerID: "naming", File: "internal/repo/lead.go"},
			},
			wantKept:       []string{"internal/repo/lead.go"},
			wantSuppressed: 0,
		},
		{
			name:           "no findings at all",
			files:          files,
			findings:       nil,
			wantKept:       nil,
			wantSuppressed: 0,
		},
		{
			name:  "every finding suppressed leaves an empty set with a count",
			files: files,
			findings: []core.Finding{
				{AnalyzerID: "shadowing", File: "internal/dbgen/lead.sql.go"},
				{AnalyzerID: "shadowing", File: "internal/dbgen/task.sql.go"},
			},
			wantKept:       nil,
			wantSuppressed: 2,
		},
	}
}

// TestSplitGeneratedUnlistedFile covers what a delegated linter does: it
// reports across the whole module, so it names files the changed set never
// listed. Those still have to be judged, or the hook path leaks generated
// noise back in.
func TestSplitGeneratedUnlistedFile(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFileAt(t, dir, "gen.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage x\n")
	writeFileAt(t, dir, "hand.go", "package x\n")

	ctx := &core.AnalysisContext{
		ChangedFiles: nil, // nothing changed: both files are unlisted
		Sources:      core.NewSourceProvider(dir),
	}
	findings := []core.Finding{
		{AnalyzerID: "golangci-lint", File: "gen.go"},
		{AnalyzerID: "golangci-lint", File: "hand.go"},
		{AnalyzerID: "golangci-lint", File: "missing.go"},
	}

	got := splitGenerated(ctx, findings)
	if got.SuppressedGenerated != 1 {
		t.Fatalf("SuppressedGenerated = %d, want 1", got.SuppressedGenerated)
	}
	if len(got.Findings) != 2 {
		t.Fatalf("kept %d findings, want 2: %+v", len(got.Findings), got.Findings)
	}
}

func TestAnalyzeIncludeGeneratedKeepsEverything(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	gitInitRepo(t, dir)
	emDash := "\u2014"
	writeFileAt(
		t,
		dir,
		"gen.go",
		"// Code generated by sqlc. DO NOT EDIT.\n\npackage x\n\n// a note "+emDash+" here\n",
	)
	runGitAt(t, dir, "add", "gen.go")

	repo, err := vcs.Open(dir)
	if err != nil {
		t.Fatalf("vcs.Open: %v", err)
	}

	testCases := []struct {
		name             string
		includeGenerated bool
		wantFindings     bool
		wantSuppressed   bool
	}{
		{
			name:             "suppressed by default",
			includeGenerated: false,
			wantFindings:     false,
			wantSuppressed:   true,
		},
		{
			name:             "reported with include-generated",
			includeGenerated: true,
			wantFindings:     true,
			wantSuppressed:   false,
		},
	}
	for _, testCase := range testCases {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()

			cfg := config.Defaults()
			cfg.ApplyPreset()
			cfg.IncludeGenerated = testCase.includeGenerated

			result := NewSession(repo, "", nil, cfg).Analyze(ScopeChanged, nil, FileSetChanged)

			hasEmDash := false
			for _, f := range result.Findings {
				if f.AnalyzerID == "typographic-markers" {
					hasEmDash = true
				}
			}
			if hasEmDash != testCase.wantFindings {
				t.Fatalf(
					"typographic-markers finding present = %v, want %v",
					hasEmDash,
					testCase.wantFindings,
				)
			}
			if (result.SuppressedGenerated > 0) != testCase.wantSuppressed {
				t.Fatalf(
					"SuppressedGenerated = %d, want suppression = %v",
					result.SuppressedGenerated,
					testCase.wantSuppressed,
				)
			}
		})
	}
}
